spring:
  profiles:
    active: dev

  # ?? ??
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---
# ?? ??
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/matzip_dev
    username: matzip_dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---
# ?? ??
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:jdbc:mysql://production-db-server:3306/matzip}
    username: ${DB_USERNAME:matzip_user}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:production-redis-server}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}